logging:
  level:
    ROOT: DEBUG
    org.springframework.web: DEBUG
server:
  port: 0
spring:
  application:
    name: party-management-webservice
  cloud:
    consul:
      enabled: true
      port: 8500
      discovery:
        enabled: true
        register: true