logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO
server:
  address: 192.168.56.1
  port: 9898
spring:
  application:
    name: party-management-webservice
  cloud:
    consul:
      host: 192.168.33.50
      enabled: true
      port: 8500
      discovery:
        enabled: true
        register: true
        hostname: 192.168.56.1